In [1]:
import torch

embeddings = torch.nn.Embedding(10, 5)

In [7]:
embeddings(torch.tensor([0])).shape

torch.Size([1, 5])

In [9]:
embeddings(torch.tensor([0, 3])).shape

torch.Size([2, 5])

In [11]:
tensor = torch.tensor([2, 3, 4, 5])
tensor[:1]

tensor([2])

In [3]:
import word_vectorization.models.word2vec.Word2Vec as Word2Vec

trainFileName = './data/W2vData/train.csv'
testFileName = './data/W2vData/test.csv'

word2VecModel = Word2Vec.Word2Vec(2, trainFileName, embeddingSize=300, k=3)
word2VecEmbeddings = word2VecModel.train(epochs=10, lr=0.005, batchSize=2**12, verbose=True)

Loaded training data. Vocabulary size: 17240
Saved embeddings not found. Starting training from scratch.


/home/ashmitchamoli/.local/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Training:   5%|▌         | 8/160 [00:06<02:06,  1.20it/s]


KeyboardInterrupt: 

In [4]:
import word_vectorization.datasets.ClassificationDataset as ClassificationDataset

trainDataset = ClassificationDataset.ClassificationDataset(trainFileName, word2VecModel.wordIndices)
testDataset = ClassificationDataset.ClassificationDataset(testFileName, word2VecModel.wordIndices)

In [5]:
testDataset.tokenizedSentences

[tensor([ 2169,  9806,  2283, 12327, 16232,  9429, 10465,  8233,  9485,     0,
          5108,     0,     0, 13231,  8890,  6808, 15663,  9663, 13238,  1303,
          3582,     0,     0]),
 tensor([14149,  6095,     0,     0, 14352,     0,     0,  3258,     0,     0,
             0, 10360, 12056,  3391,  5919,  1878,  5924, 17204,  2046,     0,
             0,  5100,     0,     0, 13082,  6034, 14264,  1034, 16585,     0,
             0, 10360, 12844, 17204, 16077,  8828,    -1, 14149,  7281,     0,
             0,  4995, 10015,  1140,  2046,  9836,  6986,  4232, 17204,  3342,
          3578,  1878,     0,     0]),
 tensor([14701,     0,     0, 10360,  4034,  8340,  3584, 10360, 12389,  8764,
         12327,  2046, 16552,  5919, 16751,  2104, 10360,  5922,  5802, 10644,
         10360,  9494,  5919,  3720, 16391, 10908,     0,     0, 16967,  9485,
          8341, 11857,  5919,    -1,  4985,     0,     0,  2046,  1596, 16398,
          5919, 11244,     0,     0]),
 tensor([14701,     0